version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5455:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: "5455"
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: 1

volumes:
  db_data: